### ISSUE TITLE
Window overlays when creating projects (minor enhancement)

### ISSUE THREAD

**Issue by Prospero100** [jlattimer/D365DeveloperExtensions#10]
This is a minor issue I've noticed when testing the latest release. When creating new projects there is sometimes a clash of popups/overlays so that the window you need to update is underneath a window waiting for the response.

e.g when creating a plugin test project the window that asks for the SDK version to use is pushed to the back, when it should be the active window. No big issue, but it would be an enhancement to make sure the relevant popup is active and on top.

![image](https://user-images.githubusercontent.com/13137296/36203563-e36fa1a4-117f-11e8-99c7-dcc3189d2140.png)

**Comment by jlattimer** [comment]
Hopefully fixed
