### ISSUE TITLE
Plugin deployer: unable to publish an assembly using spkl

### ISSUE THREAD

**Issue by KimBon** [jlattimer/D365DeveloperExtensions#13]
Hi

Thanks a lot for all the work you are doing to make this great addon work on VS2017.

With the latest (beta) version, I am able to connect with Plugin Deployer to my V9 trial. However, If I hit publish I cannot register my new assembly using the spkl setting (as new assembly or just to update).

If I add the spkl package to the same project, I can register the assembly via the deploy-plugins.bat file of spkl. 

My test class is this:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Xrm.Sdk;

namespace CustomerTest.ProjectX.Plugin.Account
{
    [CrmPluginRegistration(MessageNameEnum.Create, "account", StageEnum.PreValidation, ExecutionModeEnum.Synchronous, "", "ValidateAddressCreate", 1, IsolationModeEnum.Sandbox)]
    [CrmPluginRegistration(MessageNameEnum.Update, "account", StageEnum.PreValidation, ExecutionModeEnum.Synchronous, "address1_city", "ValidateAddressUpdate", 1, IsolationModeEnum.Sandbox)]
    public class ValidateAddress : IPlugin
    {
        public ValidateAddress()
        {
        }

        public void Execute(IServiceProvider serviceProvider)
        {
            throw new NotImplementedException("test3");
        }
    }
}

```

Just wondering if there is something I am doing wrong, or this is an issue in this release?

Thanks

Kim

**Comment by jlattimer** [comment]
Should be fixed in the next release

**Comment by KimBon** [comment]
does it mean it should be fixed in latest new initial release?

**Comment by jlattimer** [comment]
Hopefully :)
