### ISSUE TITLE
VS 2017 installation prerequisites

### ISSUE THREAD

**Issue by os008** [jlattimer/D365DeveloperExtensions#14]
When trying to install the extension on VS 2017, the checkbox to select VS 2017 is dimmed, and I get the following message: "The extension cannot be installed to this product due to prerequisites that cannot be resolved."

I have VS v15.3.5.

**Comment by KimBon** [comment]
I was able to install it on VS Pro 15.5.7. Maybe you could try to first update your VS version and try again?

**Comment by os008** [comment]
Updating to v15.5.7 worked. Thank you.

**Comment by jlattimer** [comment]
Does it state which prerequisite(s)? 
These should be the items required: https://github.com/jlattimer/D365DeveloperExtensions/wiki/Prerequisites

**Comment by KimBon** [comment]
I already had 4.6.2 and specific workloads, however option was disabled.
Thought updating to latest version was worth the try and it worked. Not sure why this was necessary
