### ISSUE TITLE
Missing window "Connecting from a tool window"

### ISSUE THREAD

**Issue by os008** [jlattimer/D365DeveloperExtensions#15]
I can't find the window mentioned in the Wiki in VS.

"Ensure the panel displaying Project, Profile, and Connect is visible (there is an ex pander on the left side)."

**Comment by jlattimer** [comment]
Open a Visual Studio solution, right click and look for D365 Developer Extensions at the bottom of the menu

**Comment by jlattimer** [comment]
Updated the wiki to reflect this as well
