### ISSUE TITLE
Settings in tools section in VS 2015 are  not visible

### ISSUE THREAD

**Issue by mkalinov** [jlattimer/D365DeveloperExtensions#16]
Hi,
When I open tools/options/D365DevEx the table with settings is visible only in initial click. If move to next setting nd then back I see only grey screens.
Hope screenshot is fine to explain:
![image](https://user-images.githubusercontent.com/10182226/36866692-048cead0-1d61-11e8-8dcb-03ed438a90a5.png)

**Comment by jlattimer** [comment]
Fixed in next release
