### ISSUE TITLE
Plugin Deployer fails with VS crash

### ISSUE THREAD

**Issue by Prospero100** [jlattimer/D365DeveloperExtensions#17]
I'm not sure if I've got a configuration setting wrong somewhere, but I can't seem to get the plugin deployer to work. Each time I click "Publish" I get an initial overlay showing "deploying", and then VS locks up.

![image](https://user-images.githubusercontent.com/13137296/36895484-f20f3588-1e06-11e8-8fc6-7bd7c133d31f.png)

Here's what I've tried so far:

- Deployment Type: spkl
- Deployment Type: Assembly only
- Checked & Updated the path to the Plugin Registration Tool, used a few different formats.... tried trailing slashes on the path names and also using the full path incl executable

![image](https://user-images.githubusercontent.com/13137296/36895756-f8a49d1a-1e07-11e8-8ae4-478f0c0a910f.png)

Logging out to the Tooling and D365 logs doesn't show any errors or issues. 
Clicking on the "registration tool" in the toolbar successfully opens the registration tool. 

Manually registering my plugins works OK, similarly registering them using Spkl works OK too.

**Comment by rappen** [comment]
I get that too...
Online org 9.0.1
Deployment type: Assembly only
Clicking Publish kills VS

**Comment by Prospero100** [comment]
Also - I meant to say - I saw this initially on the beta release, but it is also an issue on the new release too (2.0.1860.1454)

CRM online v9, but also against CRM online v8. My gut feeling is that it is not getting as far as the communication with CRM. I think the issue is the interplay between VS and the plugin reg tool. 

Jason - I'm going to have a look at the code base and see if I can find the point of failure, any thoughts or advice on where to focus?

**Comment by Prospero100** [comment]
I've done some more debugging. I didn't work out how best to fix the problem, but I think I've found root cause. The issue happens when ILMerge has been used to create a combined assembly. That seems to trip up the assembly reflection code that works out what plugin implementations are in the dll. 

Using a simpler assembly, with no ILMerge in play, the plugin deployer works fine.

The error returned is "_Could not load file or assembly 'MyCompany.Dynamics.Plugins.MyLovelyPlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=2547f85175faf6bf' or one of its dependencies. The system cannot find the file specified._"

Specifically this is coming from Reflection.cs line 79:
` var types = assembly.DefinedTypes.Where(p => p.GetInterfaces().FirstOrDefault(a => a.Name == interfaceName.Name) != null);`

assembly.DefinedTypes throws the exception.

What I'm not seeing is how to change this behaviour - all referenced types are bundled up inside the same DLL. The DLL itself works fine, it's just the reflection that needs helping to understand the merged types. (I think!!)

**Comment by jlattimer** [comment]
I've merged in your change and worked around the issue when debugging
