### ISSUE TITLE
Error message in install with VS 2017

### ISSUE THREAD

**Issue by sebastiensapet** [jlattimer/D365DeveloperExtensions#19]
Hello,

When trying to install in VS 2017 pro 15.2 i get the error message : 
the extension cannot be installed to this product due to prerequisites that cannot be resolved

Sebastien.

**Comment by jlattimer** [comment]
Does it say which one?

**Comment by sebastiensapet** [comment]
Please find attach a screenshot
![sans titre 1](https://user-images.githubusercontent.com/30295017/37101299-7e13cf90-2225-11e8-8ecf-56580c3cf59d.jpg)

**Comment by jlattimer** [comment]
Can you look through these and see if any are missing?

[https://github.com/jlattimer/D365DeveloperExtensions/wiki/Prerequisites](https://github.com/jlattimer/D365DeveloperExtensions/wiki/Prerequisites)

**Comment by sebastiensapet** [comment]
Ok sorry it's my fault I don't have framework 4.6.2 just 4.6.1...

**Comment by jlattimer** [comment]
Let me know if that's it or not. I would have thought that not having the correct framework version would have been explicitly called out. Good chance though I haven't set up the prerequisites properly...

**Comment by sebastiensapet** [comment]
I'm blocked by group policy and can't install 4.6.2 :(

**Comment by jlattimer** [comment]
Removing the dependency on .NET 4.6.2 in the next release
