### ISSUE TITLE
Status Update

### ISSUE THREAD

**Issue by adgriffi** [jlattimer/D365DeveloperExtensions#2]
Hi Jason,

Been using these tools for a while (previous iteration), and looking forward to VS2017 support. Actually had to make some small modifications as we use it in an offline installation -- meaning it can't access NuGet, and the URL for NuGet was hard-coded. Modified it so it could pull from a local NuGet repository.

Anyhow, just wondering if you have a status update? Is there potential for a release any time soon?

Thanks again!
Adam

**Comment by jlattimer** [comment]
Working on it every chance I have right now. Would really like to have it out in September. I think I'll try to tap into the internal VS list of Nuget feeds on this one so it will use whatever you've got in your VS options.

**Comment by bennyboy23** [comment]
Hi Jason,
Love your work, any chance of an update with where you're at with the project currently?
Appreciate that you're only working on this when youve got time.

Thanks,
Ben

**Comment by jlattimer** [comment]
Real close to getting the first beta out actually - hoping for the first part of next week. Just trying to finish up some clean up and refactoring then I'll be ready to turn people loose on it.

**Comment by haseeb20** [comment]
Hi Jason,
Any new updates for the extension. I would love to test the first version of new extension tools :)

Thanks,
Haseeb

**Comment by jlattimer** [comment]
The first beta release is now up - test away!
