### ISSUE TITLE
Webresource Deployer: Publish locked file makes it empty

### ISSUE THREAD

**Issue by KimBon** [jlattimer/D365DeveloperExtensions#20]
Hi

We were trying the webresource deployer. When publishing a locked file, the file in CRM becomes empty. Is this expected behavior?

When we refresh to get all solution items, the default value for locked is true, which might result in empty webresources on CRM.

Kind regards

Kim

**Comment by jlattimer** [comment]
Can you provide a step by step repro?

**Comment by KimBon** [comment]
1) connect to D365
2) choose solution
3) items are refreshed, lock becomes true for all
4) make a change to one of the files
5) mark it for Publish
6) Publish
7) check results in D365

**Comment by jlattimer** [comment]
I'm not able to repro. 

1. I made a new JS file and added it to a new solution
2. Excluded it from the project 
3. Restarted VS
4. Opened solution & Web Resource Deployer
5. Connected to D365
6. After items loaded, changed to new solution
7. Item showed as locked as expected
8. From the file system, made an edit to the JS file
9. Marked for Publish
10. Publish
11. The edit to the file was reflected in D365

Is there something I'm missing?

**Comment by jlattimer** [comment]
Anything else to add? Otherwise I'm going to close this one out.

**Comment by jlattimer** [comment]
Closed

**Comment by alano444** [comment]
I am having this issue now.  Visual Studio 2017. If I repeat jlattimer 's 11 steps above, I get an empty file
