### ISSUE TITLE
"Use Map File?" disabled

### ISSUE THREAD

**Issue by devkeydet** [jlattimer/D365DeveloperExtensions#23]
I have the "Solution Packager" tool window working with a "web site" project. Everything works as expected.  It unpacks the files into the "web site" project.  I added a mapping.xml file manually (since the item template isn't available for "web site" projects.  However, I cannot enable the "Use Map File?" option in the "Solution Packager" tool window.

Here's what my mapping.xml looks like:
```
<?xml version="1.0" encoding="utf-8"?>
<Mapping>
  
  <!-- Keep the filename as mapping.xml - this is the only way it will be used during pack & extract operations -->-->
  
  <!--https://msdn.microsoft.com/en-us/library/jj602987.aspx-->
  
  <!-- Match specific named files to an alternate folder -->
  <!--<FileToFile map="YourPlugin.dll" to="..\..\Plugins\bin\**\YourPlugin.dll" />
  <FileToFile map="YourWorkflow.dll" to="..\..\YourWorkflow\bin\**\SomeWorkflow.dll" />-->
  <!-- Match any file in and under WebResources to an alternate set of sub-folders -->
  <FileToPath map="WebResources\*.*" to="..\..\WebResources\**" />
  <FileToPath map="WebResources\**\*.*" to="..\..\WebResources\**" />
</Mapping>
```

Here is the option disabled:
![image](https://user-images.githubusercontent.com/4499296/38469264-d6a1e576-3b1f-11e8-9776-75d3584a36d6.png)

Am I missing a step?

**Comment by devkeydet** [comment]
I just tried this using your template for the solution package project and map file and still see a disabled checkbox for "Use Map File?".

**Comment by jlattimer** [comment]
Fixed - just forgot to actually enable the button
