### ISSUE TITLE
d365 typescript project cannot detect node.js

### ISSUE THREAD

**Issue by bennyboy23** [jlattimer/D365DeveloperExtensions#39]
I have node installed on my machine and installed the nodejs development component for vs2017
![image](https://user-images.githubusercontent.com/6200604/43322039-7801420a-91a5-11e8-8daa-42e4b3d02076.png)

**Comment by jhoefnagels** [comment]
I had the same problem. The tooling executes a "npm view" command after which the response is parsed using json. My npm output wasn't in json so the parsing failed throwing the error that NPM is not installed.
You could try and set your default output of npm to json by running "npm config set json=true".
Now the result of the command "npm view @types/xrm" should be in json.

Is is recommended that "--json" option is added to the view command so the result will work regardless of the user config.

**Comment by bennyboy23** [comment]
This worked a treat thank you
