### ISSUE TITLE
Add "ASP.NET and web development" dependency to documentation

### ISSUE THREAD

**Issue by Naeloo** [jlattimer/D365DeveloperExtensions#5]
Hi!

Thanks for the beta version - it is working pretty good so far.

Only a small suggestion - when you try to create a Web Resource project from the template and "ASP.NET and web development" is not installed into VS2017 there will be a somewhat cryptic "The template specified cannot be found. Please check that the full path is correct" error, presumably due to VS being unable to recognize the webproj file.

This may seem like a dumb mistake and straightforward but starting from a blank VS2017 installation and coffee-deprived it left me looking through the plugin installation directory for a while, so I'd suggest adding it to the Wiki or the README as a dependency to prevent confusion. It can quite easily be installed afterwards by using Tools=>"Get Tools and Features..."

Cheers and Thanks Again

**Comment by jlattimer** [comment]
I added in some dependency checks when installing the extension to ensure the web stuff was installed and added a check to ensure NPM was installed as that would have also failed with a non-descriptive error when creating a TS project.
