### ISSUE TITLE
Downloading Web Resources does not follow proper file path

### ISSUE THREAD

**Issue by jdimarzio** [jlattimer/D365DeveloperExtensions#7]
my web resources are named with a file structure.  When i download them from CRM, the file structure is not maintained, and only the 'file name' is kept

**Comment by jlattimer** [comment]
You could use the Download All button (folder w/ blue arrow) and it will download everything in the current view and create folders matching what CRM has. Or else you could pre-create folders and right-click on the download arrow button and it will let you choose which folder to place it in.

Would either of those things work?

**Comment by jdimarzio** [comment]
Thanks @jlattimer , right click and specify would work for me!

**Comment by jlattimer** [comment]
Closing :)
